#!/bin/bash

source /opt/ros/jazzy/setup.bash

cd "${RMCS_PATH}"/rmcs_ws || exit

[[ -x /opt/cmake/bin/cmake ]] &&
    export PATH="/opt/cmake/bin:$PATH"

command -v clang &>/dev/null &&
    export CC=clang

command -v clang++ &>/dev/null &&
    export CXX=clang++

colcon_args="--event-handlers console_cohesion+ --symlink-install --merge-install"
cmake_args="-G Ninja -DCMAKE_MESSAGE_LOG_LEVEL=ERROR -DCMAKE_INSTALL_MESSAGE=NEVER"

CLICOLOR_FORCE=1 NINJA_STATUS="" colcon build ${colcon_args} "$@" --cmake-args ${cmake_args}
