#! /bin/bash


source /opt/ros/humble/setup.bash

cd /workspaces/RMCS/rmcs_ws


if [ -d "src/livox_ros_driver2" ]; then
 colcon build  --merge-install --packages-select livox_ros_driver2 fast_gicp
    if [ $? -eq 2 ]; then
    exit 2
    fi
fi 

if [ -d "src/rmcs_slam" ]; then
colcon build  --merge-install --packages-select rmcs_slam 
 if [ $? -eq 2 ]; then 
    exit 2
    fi
fi

if [ -d "src/rmcs_map" ]; then
colcon build  --merge-install --packages-select rmcs_map 
 if [ $? -eq 2 ] ; then
    exit 2
    fi
fi
if [ -d "src/rmcs_location" ]; then
colcon build  --merge-install --packages-select rmcs_location 
 if [ $? -eq 2 ]; then 
    exit 2
    fi
fi
if  [ -d "src/tlarc" ]; then
colcon build --symlink-install --merge-install --packages-select tlarc 
 if [ $? -eq 2 ]; then
    exit 2
    fi
fi

if [ $? -eq 0 ]; then
    exit 0
elif [ $? -eq 2 ]; then
    exit 2
elif sudo grep -q "^$(whoami)" /etc/sudoers; then
    echo "install dependencies..."
    
    sudo apt-get update  
    sudo apt-get install -y  ros-humble-pcl-conversions ros-humble-pcl-ros libeigen3-dev dotnet-sdk-8.0  
    
    source /opt/ros/humble/setup.bash

    cd /workspaces/RMCS/rmcs_ws

    colcon build --symlink-install --merge-install --packages-select livox_ros_driver2 fast_gicp&&
    colcon build --symlink-install --merge-install --packages-select rmcs_slam &&
    colcon build --symlink-install --merge-install --packages-select rmcs_map &&
    colcon build --symlink-install --merge-install --packages-select rmcs_location
else
    echo "当前用户不具有 sudo 权限, 需要安装依赖,请将用户添加进sudoer组"
    exit -1
fi



