#!/bin/sh

if [ "$#" -ne 1 ]; then
    echo "用法: $0 <用户名>"
    echo "示例: $0 user"
    exit 1
fi

REMOTE_PLAYER="vlc"

REMOTE_USER="$1"
REMOTE_HOST="localhost"

REMOTE_PATH="/tmp/auto_aim.sdp"
LOCAL_PATH="/tmp/auto_aim.sdp"

scp remote:${REMOTE_PATH} ${REMOTE_PATH}
if [ $? -ne 0 ]; then
    echo "⚠️ 从 remote 拷贝失败。是否继续？(y/n)"
    read -r answer
    case "$answer" in
    [Yy]*) echo "继续执行后续操作…" ;;
    *)
        echo "已取消。"
        exit 1
        ;;
    esac
fi

scp "${REMOTE_PATH}" "${REMOTE_USER}@${REMOTE_HOST}:${LOCAL_PATH}"
if [ $? -ne 0 ]; then
    echo "❌ scp 拷贝失败"
    exit 1
fi

echo "✅ 文件已拷贝到宿主机：${LOCAL_PATH}"

ssh -f "${REMOTE_USER}@${REMOTE_HOST}" "DISPLAY=:0 ${REMOTE_PLAYER} '${LOCAL_PATH}'"
