#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"

{
    printf 'source /root/env_setup.bash\n'
    cat "${SCRIPT_DIR}/local-context"
} | ssh remote bash -s -- "$@"
