#!/bin/bash

SRC_DIR=/workspaces/RMCS/rmcs_ws/install
DST_DIR=ssh://remote//rmcs_install

unison -ignorearchives -auto -batch -repeat watch -times "${SRC_DIR}" "${DST_DIR}" -force "${SRC_DIR}" -follow 'Name *'
