services:
  rmcs-develop:
    image: qzhhhi/rmcs-develop:latest
    user: "1000:1000"
    privileged: true
    volumes:
      - /dev:/dev:bind
      - /tmp/.X11-unix:/tmp/.X11-unix:bind
      - /run/user/1000/wayland-0:/run/user/1000/wayland-0:bind
      - ${HOME}/.config/opencode:${CONTAINER_HOME}/.config/opencode:cached
      - ${HOME}/.config/nvim:${CONTAINER_HOME}/.config/nvim:cached
      - ${HOME}/.local/share/nvim:${CONTAINER_HOME}/.local/share/nvim:cached
      - .:/workspaces/RMCS:bind
    environment:
      - DISPLAY=${DISPLAY}
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
    network_mode: host
    tty: true
    stdin_open: true
