rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs::AutoAimPlayerComponent -> auto_aim_player
      # - rmcs::AutoAimVideoPlayerComponent -> auto_aim_video_player
      # - rmcs::AutoAimRecorderComponent -> auto_aim_recorder
      - rmcs::AutoAimComponent -> auto_aim_component

auto_aim_player:
  ros__parameters:
    input_path: "/workspaces/RMCS/develop_ws/record/26uc-train/2026-08-03_20-51-11"
    loop_play: true

auto_aim_video_player:
  ros__parameters:
    input_path: "/workspaces/data/autoaim/静止看前哨站.avi"
    framerate: 80.0
    loop_play: true

auto_aim_recorder:
  ros__parameters:
    output_path: "/tmp/autoaim/records"
    queue_depth: 16
    flush_every_n_frames: 64
    max_duration_seconds: 0
    max_videos_size_gb: 0.0
    auto_record: false

auto_aim_component:
  ros__parameters:
    dangerous_fallback: "blue"
    manual_shoot: false
    enable_rune: true
    track_ids: [HERO, ENGINEER, INFANTRY_3, INFANTRY_4, SENTRY, OUTPOST, RUNE]
    camera_translation: [0., 0., 0.]

    fire_control:
      bullet_speed: 22.5
      shoot_delay: 0.0
      offset_yaw: 0.0
      offset_pitch: 0.0
      attack_window: 60.0
      degraded_angle_speed: 12.0
      window_redundancy: 0.8
      window_hysteresis: 0.2
      attack_preaim: false
      require_stable_command: true
      yaw_tolerance: 0.07
      pitch_tolerance: 0.04
      rune_idle_duration: 0.4
      rune_shoot_duration: 0.2
      # is_lazy_gimbal: false
