rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs::AutoAimPlayerComponent -> auto_aim_player
      # - rmcs::AutoAimVideoPlayerComponent -> auto_aim_video_player
      # - rmcs::AutoAimRecorderComponent -> auto_aim_recorder
      - rmcs::AutoAimComponent -> auto_aim_component

auto_aim_player:
  ros__parameters:
    input_path: "/workspaces/data/autoaim/自家大符/"
    loop_play: true

auto_aim_video_player:
  ros__parameters:
    input_path: "/workspaces/data/autoaim/robot/rotate.avi"
    framerate: 80.0
    loop_play: true

auto_aim_recorder:
  ros__parameters:
    output_path: "/tmp/autoaim/records"
    queue_depth: 16
    flush_every_n_frames: 64
    max_duration_seconds: 0
    max_videos_size_gb: 0.0

auto_aim_component:
  ros__parameters:
    dangerous_fallback: "red"
    manual_shoot: false
    camera_translation: [0., 0., 0.]

    fire_control:
      bullet_speed: 22.5
      shoot_delay: 0.0
      offset_yaw: 0.0
      offset_pitch: 0.0
      attack_window: 120.0
      degraded_angle_speed: 12.0
      window_hysteresis: 0.2
      is_lazy_gimbal: false
      attack_preaim: false
      require_stable_command: true
      yaw_tolerance: 0.07
      pitch_tolerance: 0.04
