rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::ClimberEngineer -> engineer_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmController -> arm_controller
      - rmcs_core::controller::arm::ArmSolver -> arm_solver

      - rmcs_core::referee::ImageTransmissionLink -> image_transmission

      - rmcs_core::controller::pid::PidController -> gripper_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> gripper_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> image_pitch_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> image_pitch_velocity_pid_controller
      - rmcs_core::controller::chassis::ClimberChassisController -> chassis_controller
      - rmcs_core::controller::chassis::SteeringWheelController -> steering_wheel_controller
      - rmcs_core::controller::chassis::EngineerChassisClimberController -> engineer_chassis_climber_controller

      - rmcs_core::controller::pid::ErrorPidController -> big_yaw_angle_error_pid_controller
      - rmcs_core::controller::pid::PidController -> big_yaw_velocity_pid_controller
    
      # - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster
engineer_hardware:
  ros__parameters:
    # board_serial_arm_board_top: "AF-79CF-C275-34AA-F714-8CC6-E363-5B59-FB4E"
    board_serial_arm_board_bottom: "D4-0262-9E84-E715-CADB-9894-7241"
    board_serial_little_board: "AF-4728-8B65-756E-F0CF-DBDD-D3C8-C843-2DF6"
    gripper_zero_point: 26298
    image_pitch_zero_point: 43131
    joint6_zero_point: 7804
    joint5_zero_point: 37436
    joint4_zero_point: 32721
    joint3_zero_point: 28459
    joint2_zero_point: 39898
    joint1_zero_point: 55385
    # gripper_zero_point: 26298
    # image_pitch_zero_point: 43131
    # joint6_zero_point: 43588
    # joint5_zero_point: 12873
    # joint4_zero_point: 40551
    # joint3_zero_point: 15145
    # joint2_zero_point: 42587
    # joint1_zero_point: 55821
    steering_lf_zero_point: 3051 #7168  
    steering_lb_zero_point: 6480 #2362  
    steering_rb_zero_point: 266  #4391  
    steering_rf_zero_point: 7859 #3782  
    big_yaw_zero_point: 9443

image_transmission:
  ros__parameters:
    path: /dev/ttyUSB0    

arm_controller:
  ros__parameters:
    action_profile: climber
    gripper_step: 65.0
    gripper_open_angle: 270.0
    gripper_closed_angle: 130.0
    image_pitch_qmin: -0.7
    image_pitch_qmax: 2.2

arm_solver:
  ros__parameters:
    controller_list: [pid, gravity, friction]
    joint_6_angle_kp: 65.00
    joint_6_angle_ki: 0.0
    joint_6_angle_kd: 0.04
    joint_6_vel_kp: 0.08
    joint_6_vel_ki: 0.0002
    joint_6_vel_kd: 0.000


gripper_angle_pid_controller:
  ros__parameters:
    measurement: /arm/gripper/motor/angle
    setpoint: /arm/gripper/target_theta
    control: /arm/gripper/control_vel
    kp: 4.8
    ki: 0.0
    kd: 0.0

gripper_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/gripper/motor/velocity
    setpoint: /arm/gripper/control_vel
    control: /arm/gripper/motor/control_torque
    kp: 0.08
    ki: 0.0
    kd: 0.00


image_pitch_angle_pid_controller:
  ros__parameters:
    measurement: /arm/image_pitch/motor/angle
    setpoint: /arm/image_pitch/target_theta
    control: /arm/image_pitch/control_vel
    kp: 200.0
    ki: 0.0
    kd: 0.0

image_pitch_velocity_pid_controller:
  ros__parameters:
    measurement: /arm/image_pitch/motor/velocity
    setpoint: /arm/image_pitch/control_vel
    control: /arm/image_pitch/motor/control_torque
    kp: 0.1
    ki: 0.0
    kd: 0.0

big_yaw_angle_error_pid_controller:
  ros__parameters:
    measurement: /chassis/big_yaw/target_angle_error
    control: /chassis/big_yaw/control_vel
    kp: 140.0
    ki: 0.0
    kd: 10.0
big_yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/big_yaw/velocity
    setpoint: /chassis/big_yaw/control_vel
    control: /chassis/big_yaw/control_torque
    kp: 1.8
    ki: 0.0
    kd: 0.5

chassis_controller:
  ros__parameters:
    yaw_left_limit: -1.57
    yaw_right_limit: 1.57

steering_wheel_controller:
  ros__parameters:
    mess: 35.0
    moment_of_inertia: 2.0
    vehicle_radius: 0.3238
    wheel_radius: 0.055
    friction_coefficient: 0.7
    k1: 2.958580e+00
    k2: 3.082190e-03
    no_load_power: 15.37

engineer_chassis_climber_controller:
  ros__parameters:
    front_climber_velocity: 30.0
    back_climber_velocity: 80.0
    auto_climb_support_retract_velocity: 220.0
    auto_climb_approach_chassis_velocity: 0.5
    auto_climb_support_deploy_chassis_velocity: 0.5
    auto_climb_dash_chassis_velocity: 0.5
    auto_climb_leveled_pitch_threshold: 0.09
    sync_coefficient: 10.0
    first_stair_approach_pitch: 0.568
    second_stair_approach_pitch: 0.4174   
    front_kp: 1.0
    front_ki: 0.0
    front_kd: 0.5
    back_kp: 0.5
    back_ki: 0.0
    back_kd: 0.0

value_broadcaster:
  ros__parameters:
    forward_list:
      - "/arm/gripper/motor/velocity"
      - "/arm/gripper/motor/torque"
      - "/arm/gripper/target_theta"
      - "/arm/gripper/motor/control_torque"
      - "/arm/gripper/motor/angle"
      - "/pitch_imu_angle"

    
