rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      # - rmcs_core::controller::dart::AngleController -> angle_controller
      - rmcs_core::controller::dart::DartCamera -> dart_camera
      - rmcs_core::controller::dart::AimController -> aim_controller
      - rmcs_core::controller::dart::MessagePublisher -> message_publisher

angle_controller:
  ros__parameters:
    error_reference: 25.00
    control_velocity_limit: 30

dart_camera:
  ros__parameters:
    invert_image: false
    exposure_time: 3600
    gain: 10.0161

aim_controller:
  ros__parameters:
    image_show_enable: false
    lowerlimit_H: 45.00
    lowerlimit_L: 64.00
    lowerlimit_S: 128.00
    upperlimit_H: 75.00
    upperlimit_L: 144.00
    upperlimit_S: 255.00
    yaw_aim_position: 720.00
    pitch_aim_position: 120.00

message_publisher:
  ros__parameters:
    camera_enable: true
    friction_enable: false
    cal_fps_enable: true