rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DartLauncher ->dartlauncher_hardware
      # - rmcs_core::referee::Status -> referee_status

      - rmcs_core::controller::dartlauncher::DartLaunchControl -> launch_controller

      - rmcs_core::controller::pid::PidController -> conveyor_velocity_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> friction_first_velocity_paired_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_first_left_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_first_right_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> friction_second_velocity_paired_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_second_left_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_second_right_pid_controller

      - rmcs_core::controller::dartlauncher::DartGantryController -> gantry_controller

      - rmcs_core::controller::pid::ErrorPidController -> yaw_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller
      - rmcs_core::controller::pid::CrossCoupledController -> pitch_velocity_sync_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_left_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_right_velocity_pid_controller

      - rmcs_dart_guide::DartLauncherGuidance -> dart_guidance
      - rmcs_dart_guide::LaunchDataProcess -> launch_data_controller
      - rmcs_dart_guide::DartCameraController -> camera_controller
      - rmcs_dart_guide::ImagePublisher -> camera_image_publisher
      - rmcs_dart_guide::ImagePublisher -> display_image_publisher

      - rmcs_core::controller::dartlauncher::MotorDataPublisher -> message_publisher

dartlauncher_hardware:
  ros__parameters:
    usb_pid: -1

referee_status:
  ros__parameters:
    path: /dev/ttyUSB0

gantry_controller:
  ros__parameters:
    pitch_init_angle: 37.5
    pitch_lower_limit: 23.0
    pitch_upper_limit: 39.0
    pitch_velocity_limit: 5.0

launch_controller:
  ros__parameters:
    first_velocity: 665.0
    second_velocity: 335.0
    timeout_limit_ms: 3000

dart_guidance:
  ros__parameters:
    guidelight_yaw_setpoint: 720.0

camera_controller:
  ros__parameters:
    invert_image: false
    exposure_time: 3500
    gain: 12.00
    L_H: 55.0
    L_S: 15.0
    L_V: 15.0
    U_H: 75.0
    U_S: 255.0
    U_V: 255.0

launch_data_controller:
  ros__parameters:
    default_pitch: 37.5

#broadcast
camera_image_publisher:
  ros__parameters:
    Interface_name: /dart_guide/camera/camera_image
    topic_name: /dart_guide/camera_image
    publish_freq: 60.0
    image_type: bgr8

display_image_publisher:
  ros__parameters:
    Interface_name: /dart_guide/camera/display_image
    topic_name: /dart_guide/display_image
    publish_freq: 120.0
    image_type: mono8

# pid controllers 
conveyor_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/conveyor/velocity
    setpoint: /dart/conveyor/control_velocity
    control: /dart/conveyor/control_torque
    kp: 0.0034
    ki: 0.00
    kd: 0.009373434

friction_first_velocity_paired_controller:
  ros__parameters:
    setpoint: /dart/first_friction/control_velocity
    motor1_measurement: /dart/first_left_friction/velocity
    motor1_control_error: /dart/first_left_friction/control_error
    motor2_measurement: /dart/first_right_friction/velocity
    motor2_control_error: /dart/first_right_friction/control_error
    sync_compensation: 0.0005
    error_integral_compensation: 0.00
    filter_enable: true
    cutoff: 500.0
    motor1_filtered_topic: /dart/first_left_friction/filtered_velocity
    motor2_filtered_topic: /dart/first_right_friction/filtered_velocity

friction_first_left_pid_controller:
  ros__parameters:
    measurement: /dart/first_left_friction/control_error
    control: /dart/first_left_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_first_right_pid_controller:
  ros__parameters:
    measurement: /dart/first_right_friction/control_error
    control: /dart/first_right_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_second_velocity_paired_controller:
  ros__parameters:
    setpoint: /dart/second_friction/control_velocity
    motor1_measurement: /dart/second_left_friction/velocity
    motor1_control_error: /dart/second_left_friction/control_error
    motor2_measurement: /dart/second_right_friction/velocity
    motor2_control_error: /dart/second_right_friction/control_error
    sync_compensation: 0.0005
    error_integral_compensation: 0.00
    filter_enable: true
    cutoff: 500.0
    motor1_filtered_topic: /dart/second_left_friction/filtered_velocity
    motor2_filtered_topic: /dart/second_right_friction/filtered_velocity

friction_second_left_pid_controller:
  ros__parameters:
    measurement: /dart/second_left_friction/control_error
    control: /dart/second_left_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

friction_second_right_pid_controller:
  ros__parameters:
    measurement: /dart/second_right_friction/control_error
    control: /dart/second_right_friction/control_torque
    kp: 0.005
    ki: 0.00002
    kd: 0.005
    integral_min: -200.0
    integral_max: 200.0

yaw_angle_pid_controller:
  ros__parameters:
    measurement: /dart_guide/yaw_angle_error
    control: /dart/yaw_angle/control_velocity
    kp: 0.3036926
    ki: 0.00
    kd: 0.009373434

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw_angle/velocity
    setpoint: /dart/yaw_angle/control_velocity
    control: /dart/yaw_angle/control_torque
    kp: 0.3036926
    ki: 0.00
    kd: 0.009373434

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_angle/error
    control: /dart/pitch_angle/control_velocity
    kp: 50.0
    ki: 0.001
    kd: 0.001
    integral_min: -5.0
    integral_max: 5.0

pitch_velocity_sync_controller:
  ros__parameters:
    setpoint: /dart/pitch_angle/control_velocity
    motor1_measurement: /dart/pitch_left/velocity
    motor1_control_error: /dart/pitch_left/control_error
    motor2_measurement: /dart/pitch_right/velocity
    motor2_control_error: /dart/pitch_right/control_error
    sync_compensation: 0.05
    error_integral_compensation: 0.6
    filter_enable: false
    cutoff: 500.0
    motor1_filtered_topic: /motor1/no_use
    motor2_filtered_topic: /motor2/no_use

pitch_left_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_left/control_error
    control: /dart/pitch_left/control_torque
    kp: 0.3036926
    ki: 0.000
    kd: 0.009373434

pitch_right_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_right/control_error
    control: /dart/pitch_right/control_torque
    kp: 0.3036926
    ki: 0.000
    kd: 0.009373434
