rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DartLauncher -> dart_hardware

      - rmcs_core::controller::dart::LauncherController -> launcher_controller
      - rmcs_core::controller::pid::PidController -> friction_lf_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> friction_lb_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> friction_rb_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> friction_rf_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> conveyor_velocity_pid_controller

      - rmcs_core::controller::dart::AngleTest -> angle_test
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> pitch_left_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> pitch_right_velocity_pid_controller
      
      # - rmcs_core::controller::dart::VisualGuidance -> visual_guidance
      # - rmcs_core::controller::dart::ImageSubscriber -> image_subscriber
      # - rmcs_core::controller::dart::MessagePublisher -> message_publisher

dart_hardware:
  ros__parameters:
    usb_pid: 0xc049

launcher_controller:
  ros__parameters:
    debug_enable: true
    conveyor_working_velocity: 30.00
    friction_working_velocity: 500.00

conveyor_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/conveyor/velocity
    setpoint: /dart/conveyor/control_velocity
    control: /dart/conveyor/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

friction_lf_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_lf/velocity
    setpoint: /dart/friction_lf/control_velocity
    control: /dart/friction_lf/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

friction_lb_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_lb/velocity
    setpoint: /dart/friction_lb/control_velocity
    control: /dart/friction_lb/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

friction_rb_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_rb/velocity
    setpoint: /dart/friction_rb/control_velocity
    control: /dart/friction_rb/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

friction_rf_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_rf/velocity
    setpoint: /dart/friction_rf/control_velocity
    control: /dart/friction_rf/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

angle_test:
  ros__parameters:
    yaw_velocity_limit: 30.00
    pitch_velocity_limit: 30.00

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw/velocity
    setpoint: /dart/yaw/control_velocity
    control: /dart/yaw/control_torque
    kp: 0.03436926
    ki: 0.00
    kd: 0.009373434

pitch_left_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_left/velocity
    setpoint: /dart/pitch_left/control_velocity
    control: /dart/pitch_left/control_torque
    kp: 0.03436926
    ki: 0.00
    kd: 0.009373434

pitch_right_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_right/velocity
    setpoint: /dart/pitch_right/control_velocity
    control: /dart/pitch_right/control_torque
    kp: 0.03436926
    ki: 0.00
    kd: 0.009373434

dart_camera:
  ros__parameters:
    image_show_enable: true
    invert_image: true
    exposure_time: 5000

dart_aiming:
  ros__parameters:
    image_show_enable: false
    lowerlimit_H: 50.00
    lowerlimit_L: 96.00
    lowerlimit_S: 128.00
    upperlimit_H: 70.00
    upperlimit_L: 192.00
    upperlimit_S: 255.00

message_publisher:
  ros__parameters:
    debug_enable: false