rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::DartLauncher -> dart_hardware

      - rmcs_core::controller::dart::LauncherController -> launcher_controller
      - rmcs_core::controller::pid::PidController -> conveyor_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_lf_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_rf_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_lb_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> friction_rb_velocity_pid_controller
      - rmcs_core::controller::dart::SyncController -> friction_front_velocity_sync_controller
      - rmcs_core::controller::dart::SyncController -> friction_back_velocity_sync_controller

      - rmcs_core::controller::dart::AngleTest -> angle_test
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_left_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_right_velocity_pid_controller
      - rmcs_core::controller::dart::SyncController -> pitch_velocity_sync_controller
      
      # - rmcs_core::controller::dart::VisualGuidance -> visual_guidance
      # - rmcs_core::controller::dart::ImageSubscriber -> image_subscriber
      - rmcs_core::controller::dart::MessagePublisher -> message_publisher

dart_hardware:
  ros__parameters:
    usb_pid: 0xc049

launcher_controller:
  ros__parameters:
    debug_enable: true
    conveyor_working_velocity: 120.00
    friction_working_velocity: 400.00
    error_velocity: 00.00

conveyor_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/conveyor/velocity
    setpoint: /dart/conveyor/control_velocity
    control: /dart/conveyor/control_torque
    kp: 0.0034
    ki: 0.00
    kd: 0.009373434

friction_lf_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_lf/control_error
    control: /dart/friction_lf/control_torque
    kp: 200.0
    ki: 0.00
    kd: 0.00

friction_rf_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_rf/control_error
    control: /dart/friction_rf/control_torque
    kp: 200.0
    ki: 0.00
    kd: 0.00

friction_lb_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_lb/control_error
    control: /dart/friction_lb/control_torque
    kp: 200.0
    ki: 0.0
    kd: 0.0

friction_rb_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/friction_rb/control_error
    control: /dart/friction_rb/control_torque
    kp: 200.0
    ki: 0.0
    kd: 0.0

friction_front_velocity_sync_controller:
  ros__parameters:
    setpoint: /dart/friction_front/control_velocity
    motor1_measurement: /dart/friction_lf/velocity
    motor1_control_error: /dart/friction_lf/control_error
    motor2_measurement: /dart/friction_rf/velocity
    motor2_control_error: /dart/friction_rf/control_error
    sync_compensation: 0.02
    error_integral_compensation: 0.00
    log_enable: false

friction_back_velocity_sync_controller:
  ros__parameters:
    setpoint: /dart/friction_back/control_velocity
    motor1_measurement: /dart/friction_lb/velocity
    motor1_control_error: /dart/friction_lb/control_error
    motor2_measurement: /dart/friction_rb/velocity
    motor2_control_error: /dart/friction_rb/control_error
    sync_compensation: 0.00
    error_integral_compensation: 0.00
    log_enable: false

angle_test:
  ros__parameters:
    yaw_velocity_limit: 20.00
    pitch_velocity_limit: 20.00

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw/velocity
    setpoint: /dart/yaw/control_velocity
    control: /dart/yaw/control_torque
    kp: 0.3036926
    ki: 0.00
    kd: 0.009373434

pitch_left_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_left/control_error
    control: /dart/pitch_left/control_torque
    kp: 0.3036926
    ki: 0.00
    kd: 0.009373434

pitch_right_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/pitch_right/control_error
    control: /dart/pitch_right/control_torque
    kp: 0.03436926
    ki: 0.00
    kd: 0.009373434

pitch_velocity_sync_controller:
  ros__parameters:
    setpoint: /dart/pitch/control_velocity
    motor1_measurement: /dart/pitch_left/velocity
    motor1_control_error: /dart/pitch_left/control_error
    motor2_measurement: /dart/pitch_right/velocity
    motor2_control_error: /dart/pitch_right/control_error
    sync_compensation: 0.8
    error_integral_compensation: 0.1
    log_enable: false

dart_camera:
  ros__parameters:
    image_show_enable: true
    invert_image: true
    exposure_time: 5000

dart_aiming:
  ros__parameters:
    image_show_enable: false
    lowerlimit_H: 50.00
    lowerlimit_L: 96.00
    lowerlimit_S: 128.00
    upperlimit_H: 70.00
    upperlimit_L: 192.00
    upperlimit_S: 255.00

message_publisher:
  ros__parameters:
    camera_enable: false
    friction_enable: true
    cal_fps_enable: false