rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
    - rmcs_core::hardware::CatapultDart -> catapult_dart
    - rmcs_core::controller::dart::DartSettings -> dart_settings
    - rmcs_core::controller::dart::DartLaunchController -> launch_controller
    - rmcs_core::controller::dart::Test -> actual_speed_and_control_torque_test_node
    - rmcs_core::controller::pid::PidController -> pitch_velocity_pid_controller
    - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
    - rmcs_core::controller::pid::PidController -> force_pid_controller
    - rmcs_core::broadcaster::ValueBroadcaster -> Value_Broadcasters

catapult_dart:
  ros__parameters:
    usb_pid: -1
    first_sample_spot: 1.0   
    final_sample_spot: 4.0 
    trigger_runtime: 0x0000
    limiting_runtime: 0x0000
    lifting_left_runtime: 0x0000
    lifting_right_runtime: 0x0000

dart_settings:
  ros__parameters: 
    is_auto_pitch_control_mode: 0              #<0 = false = manual_control_mode> or <1 = true = double_loop_pid>
    is_auto_force_control_mode: 0              #<0 = false = manual_control_mode> or <1 = true = force_sensor>
    pitch_angle_kp: 1.0
    pitch_angle_ki: 0.0
    pitch_angle_kd: 0.0
    force_control_kp: 0.5
    force_control_ki: 0.0
    force_control_kd: 0.0
    max_transform_rate: 20.0

launch_controller:
  ros__parameters:
    belt_velocity: 10.0
    lifting_velocity: 10.0
    sync_coefficient: 0.5
    lifting_sync_coefficient: 0.5
    b_kp: 1.0
    b_ki: 0.0
    b_kd: 0.0
    max_control_torque: 2.5
    trigger_free_angle: 0x0E2A
    trigger_lock_angle: 0x0FC1
    lifting_up_angle_left:      0x06D7
    lifting_down_angle_left:    0x0DAA
    lifting_up_angle_right:     0x08C9
    lifting_down_angle_right:   0x0C05
    limiting_wait_time:   0x0001
    limiting_free_angle_: 0x0001
    limiting_lock_angle_: 0x0001


actual_speed_and_control_torque_test_node:
  ros__parameters:
    lifting_up_angle_left:      0x06D7
    lifting_down_angle_left:    0x0DAA
    lifting_up_angle_right:     0x08C9
    lifting_down_angle_right:   0x0B05

pitch_velocity_pid_controller:
  ros__parameters: 
    measurement: /dart/pitch_motor/velocity
    setpoint: /pitch/control/velocity
    control: /dart/pitch_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw_motor/velocity
    setpoint: /yaw/control/velocity
    control: /dart/yaw_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0

force_pid_controller:
  ros__parameters:
    measurement: /dart/force_control_motor/velocity
    setpoint: /force/control/velocity
    control: /dart/force_control_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0

Value_Broadcasters:
  ros__parameters:
    forward_list:
      # - "/dart/pitch/angle"
      - "/dart/force_control_motor/velocity"
      - "/imu/catapult_roll_angle"
      - "/imu/catapult_pitch_angle"
      - "/imu/catapult_yaw_angle"