rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::controller::dart::DartCamera -> dart_camera
      - rmcs_core::controller::dart::DartAiming -> dart_aiming
      # - rmcs_core::controller::dart::MessagePublisher -> message_publisher

dart_camera:
  ros__parameters:
    image_show_enable: true
    invert_image: true
    exposure_time: 1000

dart_aiming:
  ros__parameters:
    image_show_enable: false
    lowerlimit_H: 60.00
    lowerlimit_L: 128.00
    lowerlimit_S: 60.00
    upperlimit_H: 80.00
    upperlimit_L: 196.00
    upperlimit_S: 255.00
