rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::CatapultDartCBoard -> dart_hardware
      - rmcs_dart_guidance::manager::RemoteCommandBridge -> remote_command_bridge
      - rmcs_dart_guidance::manager::DartManager -> dart_manager
      - rmcs_core::controller::dart::BeltController -> belt_controller
      - rmcs_core::controller::dart::TriggerController -> trigger_controller
      - rmcs_core::controller::dart::FillingController -> filling_controller

dart_hardware:
  ros__parameters:
    board_serial_top_board: ""

belt_controller:
  ros__parameters:
    belt_slow_down_velocity: 0.0
    belt_fast_down_velocity: 0.0
    belt_up_soft_stage1_velocity: 0.0
    belt_up_soft_stage2_velocity: 0.0
    belt_up_soft_stage3_velocity: 0.0
    belt_up_stage1_velocity: 0.0
    belt_up_stage2_velocity: 0.0
    slider_rail_length: 1.0
    soft_stage1_persent: 0.3
    soft_stage2_persent: 0.8
    part_persent: 0.5
    belt_stall_ticks: 50
    belt_stall_velocity_threshold: 0.1
    belt_stall_torque_threshold: 9999.0

trigger_controller:
  ros__parameters:
    trigger_free_angle: 0.0
    trigger_lock_angle: 0.0
    carriage_velocity: 0.0
    carriage_calibrate_velocity: 0.0
    carriage_position_kp: 0.0
    carriage_position_ki: 0.0
    carriage_position_kd: 0.0
    carriage_position_integral_max: 0.0
    carriage_position_tolerance: 10
    carriage_position_settle_ticks: 250
    carriage_stall_ticks: 50
    carriage_stall_velocity_threshold: 0.1
    carriage_stall_torque_threshold: 9999.0

filling_controller:
  ros__parameters:
    lift_control_velocity: 0.0
    lift_stall_ticks: 50
    lift_stall_velocity_threshold: 0.1
    lift_stall_torque_threshold: 9999.0
    limit_free_angle: 0
    limit_lock_angle: 0
    limit_complete_ticks: 100
    limit_pulse_ticks: 100
