rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::CatapultDart -> dart_hardware
      # - rmcs_core::controller::dart::DartLaunchController -> launch_controller
      - rmcs_core::hardware::ServoTest -> servo_test
      - rmcs_core::controller::pid::PidController -> pitch_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> force_pid_controller
      # - rmcs_core::controller::dart::DartSettings -> dart_settings
      # - rmcs_core::broadcaster::ValueBroadcaster -> broadcaster

# broadcaster:
#   ros__parameters:
#     forward_list:
#       - /dart/force_control_motor/control_velocity
#       - /dart/drive_belt/left/control_torque
#       - /dart/drive_belt/left/velocity
#       - /dart/drive_belt/right/control_torque
#       - /dart/drive_belt/right/velocity
#       - /dart/force_control_motor/velocity

dart_hardware:
  ros__parameters:
    usb_pid: -1
    first_sample_spot: 1.0   
    final_sample_spot: 4.0 

# launch_controller:
#   ros__parameters:
#     belt_velocity: 10.0
#     sync_coefficient: 0.5
#     b_kp: 1.0
#     b_ki: 0.0
#     b_kd: 0.0
#     max_control_torque: 1.0
#     trigger_free_angle: 0x0E2A
#     trigger_lock_angle: 0x0FC1

servo_test:
  ros__parameters:
    trigger_free_angle: 0x0E2A
    trigger_lock_angle: 0x0FC1
    lifting_up_angle_left:      0x073E
    lifting_middle_angle_left:  0x073E
    lifting_down_angle_left:    0x0D18
    lifting_up_angle_right:     0x11DB
    lifting_middle_angle_right: 0x11DB
    lifting_down_angle_right:   0x0C52

# dart_settings:
  # ros__parameters:
    # log_enable: false
    # screw_max_velocity: 10.0

pitch_velocity_pid_controller:
  ros__parameters: 
    measurement: /dart/pitch_motor/velocity
    setpoint: /pitch/control/velocity
    control: /dart/pitch_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw_motor/velocity
    setpoint: /yaw/control/velocity
    control: /dart/yaw_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0

force_pid_controller:
  ros__parameters:
    measurement: /dart/force_control_motor/velocity
    setpoint: /force/control/velocity
    control: /dart/force_control_motor/control_torque
    kp: 1.0
    ki: 0.0
    kd: 0.0