rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::CatapultDart -> dart_hardware

      - rmcs_dart_guidance::manager::RemoteCommandBridge -> remote_command_bridge
      - rmcs_dart_guidance::manager::DartManager -> dart_manager

      - rmcs_core::controller::dart::BeltController -> belt_controller
      - rmcs_core::controller::pid::PidController -> left_belt_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_belt_velocity_pid_controller

      - rmcs_core::controller::dart::FillingController -> filling_controller

      - rmcs_core::controller::dart::TriggerController -> trigger_controller

      - rmcs_core::controller::dart::FourZChassisController -> four_z_chassis_controller
      - rmcs_core::controller::dart::YawController -> yaw_controller
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> front_left_chassis_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> front_right_chassis_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> back_left_chassis_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> back_right_chassis_velocity_pid_controller

      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

dart_manager:
  ros__parameters:
    launch_carriage_position_1: -4350000.0
    launch_carriage_position_2: -4150000.0
    launch_carriage_position_3: -4150000.0
    launch_carriage_position_4: -4350000.0
    vision_aim_target_setpoint_1: 640.0
    vision_aim_target_setpoint_2: 640.0
    vision_aim_target_setpoint_3: 640.0
    vision_aim_target_setpoint_4: 640.0

value_broadcaster:
  ros__parameters:
    forward_list:
      - /dart/chassis/front_left_motor/velocity
      - /dart/chassis/front_right_motor/velocity
      - /dart/chassis/back_left_motor/velocity
      - /dart/chassis/back_right_motor/velocity
      - /dart/chassis/front_left_motor/torque
      - /dart/chassis/front_right_motor/torque
      - /dart/chassis/back_left_motor/torque
      - /dart/chassis/back_right_motor/torque
      - /dart/chassis/front_left_motor/control_velocity
      - /dart/chassis/front_right_motor/control_velocity
      - /dart/chassis/back_left_motor/control_velocity
      - /dart/chassis/back_right_motor/control_velocity
      - /dart/chassis/imu/pitch
      - /dart/chassis/imu/roll
      - /dart/trigger/position_motor/control_torque
      - /dart/trigger/position_motor/torque
      - /dart/trigger/position_motor/velocity
      - /dart/trigger/position_motor/angle
      - /dart/yaw/motor/velocity
      - /dart/yaw/motor/angle
      - /dart/yaw/motor/control_velocity
      - /dart/yaw/motor/control_torque
      - /dart/yaw/status
      # - /dart/trigger/position_motor/encoder_angle
      # - /dart/belt/left_motor/velocity
      # - /dart/belt/right_motor/velocity
      - /dart/belt/left_motor/angle
      - /dart/belt/right_motor/angle
      # - /dart/belt/left_motor/torque
      # - /dart/belt/right_motor/torque
      # - /dart/belt/left_motor/control_velocity
      # - /dart/belt/right_motor/control_velocity
      # - /dart/belt/left_motor/control_torque
      # - /dart/belt/right_motor/control_torque
      # - /dart/filling_lift/left_motor/torque
      # - /dart/filling_lift/right_motor/torque

dart_hardware:
  ros__parameters:
    board_serial_top_board: ""
    bottom_limit_read_period_ms: 20
    bottom_limit_pull_up: true
    bottom_limit_active_low: true
    front_left_bottom_limit_gpio_index: 4
    front_right_bottom_limit_gpio_index: 5
    back_left_bottom_limit_gpio_index: 6
    back_right_bottom_limit_gpio_index: 7

belt_controller:
  ros__parameters:
    belt_slow_down_velocity: 10.0
    belt_fast_down_velocity: 15.0
    belt_up_soft_stage1_velocity: 3.0
    belt_up_soft_stage2_velocity: 20.0
    belt_up_soft_stage3_velocity: 5.0
    belt_up_stage1_velocity: 10.0
    belt_up_stage2_velocity: 5.0
    slider_rail_length: 40.0
    soft_stage1_persent: 0.15
    soft_stage2_persent: 0.9
    part_persent: 0.45
    belt_load_torque_limit: 6.0
    belt_unload_torque_limit: 0.6
    belt_stall_ticks: 200
    belt_stall_velocity_threshold: 0.05
    belt_stall_torque_threshold: 0.5
    manual_belt_velocity_sensitivity: -10.0

left_belt_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/belt/left_motor/velocity
    setpoint: /dart/belt/left_motor/control_velocity
    control: /dart/belt/left_motor/control_torque
    output_abs_limit: /dart/belt/left_motor/control_torque_limit
    kp: 1.0
    ki: 0.0
    kd: 0.0

right_belt_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/belt/right_motor/velocity
    setpoint: /dart/belt/right_motor/control_velocity
    control: /dart/belt/right_motor/control_torque
    output_abs_limit: /dart/belt/right_motor/control_torque_limit
    kp: 1.0
    ki: 0.0
    kd: 0.0

filling_controller:
  ros__parameters:
    lift_control_velocity: 4.0
    lift_torque_limit: 1.0
    lift_stall_ticks: 150
    lift_stall_velocity_threshold: 0.1
    lift_stall_torque_threshold: 0.1
    limit_free_angle: 0x0670
    limit_lock_angle: 0x0599
    limit_complete_ticks: 100
    limit_pulse_ticks: 300
    manual_lift_velocity_sensitivity: 4.0

trigger_controller:
  ros__parameters:
    trigger_free_angle: 0.625
    trigger_lock_angle: 0.45
    trigger_action_ticks: 500
    carriage_velocity: 20.0
    carriage_torque_limit: 2.5
    calibrate_rollback: 800000
    calibrate_rollback_velocity: 15.0
    carriage_calibrate_torque_limit: 0.3
    carriage_calibrate_launch_ticks: 200
    carriage_calibrate_control_torque: 0.11
    carriage_stall_velocity_threshold: 0.00
    carriage_stall_ticks: 500
    carriage_velocity_pid_kp: 0.3
    carriage_velocity_pid_ki: 0.0
    carriage_velocity_pid_kd: 0.0
    carriage_position_kp: 0.005
    carriage_position_ki:  0.0 # 0.00025
    carriage_position_kd: 0.0
    carriage_position_integral_max: 2.0
    carriage_position_tolerance: 100
    carriage_position_settle_ticks: 500
    manual_carriage_velocity_sensitivity: 50.0

four_z_chassis_controller:
  ros__parameters:
    zero_down_speed: 50.0
    zero_rollback_speed: 50.0
    zero_rollback_angle: 80.0
    zero_hold_ticks: 500
    level_descend_speed: 25.0
    upper_soft_limit_angle: 170.0
    level_settle_ticks: 500
    level_pitch_tolerance: 0.0005
    level_roll_tolerance: 0.0005
    pitch_offset: -0.0130
    roll_offset: 0.0210
    level_correction_velocity_deadband: 50.0
    level_pitch_pid_kp: 20000.0
    level_pitch_pid_ki: 10.0
    level_pitch_pid_kd: 0.0
    level_pitch_pid_integral_min: -50.0
    level_pitch_pid_integral_max: 50.0
    level_pitch_pid_output_min: -100.0
    level_pitch_pid_output_max: 100.0
    level_roll_pid_kp: 10000.0
    level_roll_pid_ki: 10.0
    level_roll_pid_kd: 0.0
    level_roll_pid_integral_min: -50.0
    level_roll_pid_integral_max: 50.0
    level_roll_pid_output_min: -100.0
    level_roll_pid_output_max: 100.0
    level_pitch_rate_kd: 0.0
    level_roll_rate_kd: 0.0
    chassis_velocity_limit: 50.0
    chassis_torque_limit: 2.0
    manual_chassis_velocity_sensitivity: 50.0

yaw_controller:
  ros__parameters:
    vision_aim_tolerance_px: 5.0
    vision_aim_settle_ticks: 50
    vision_aim_pid_kp: 0.01
    vision_aim_pid_ki: 0.0
    vision_aim_pid_kd: 0.0
    vision_aim_pid_output_min: -50.0
    vision_aim_pid_output_max: 50.0
    yaw_torque_limit: 2.0
    manual_yaw_velocity_sensitivity: 50.0

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/yaw/motor/velocity
    setpoint: /dart/yaw/motor/control_velocity
    control: /dart/yaw/motor/control_torque
    output_abs_limit: /dart/yaw/motor/control_torque_limit
    kp: 1.0
    ki: 0.0
    kd: 0.0

front_left_chassis_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/chassis/front_left_motor/velocity
    setpoint: /dart/chassis/front_left_motor/control_velocity
    control: /dart/chassis/front_left_motor/control_torque
    output_abs_limit: /dart/chassis/front_left_motor/control_torque_limit
    kp: 0.006
    ki: 0.0
    kd: 0.0

front_right_chassis_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/chassis/front_right_motor/velocity
    setpoint: /dart/chassis/front_right_motor/control_velocity
    control: /dart/chassis/front_right_motor/control_torque
    output_abs_limit: /dart/chassis/front_right_motor/control_torque_limit
    kp: 0.006
    ki: 0.0
    kd: 0.0

back_left_chassis_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/chassis/back_left_motor/velocity
    setpoint: /dart/chassis/back_left_motor/control_velocity
    control: /dart/chassis/back_left_motor/control_torque
    output_abs_limit: /dart/chassis/back_left_motor/control_torque_limit
    kp: 0.006
    ki: 0.0
    kd: 0.0

back_right_chassis_velocity_pid_controller:
  ros__parameters:
    measurement: /dart/chassis/back_right_motor/velocity
    setpoint: /dart/chassis/back_right_motor/control_velocity
    control: /dart/chassis/back_right_motor/control_torque
    output_abs_limit: /dart/chassis/back_right_motor/control_torque_limit
    kp: 0.006
    ki: 0.0
    kd: 0.0
