rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Engineer -> engineer_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmSolver -> arm_solver
      - rmcs_core::controller::arm::ArmController -> arm_controller
      
engineer_hardware:
  ros__parameters:
    arm_board_usb_pid: 0x488d
    joint6_zero_point: 0
    joint5_zero_point: 6735
    joint4_zero_point: 10365
    joint3_zero_point: 40955
    joint2_zero_point: 38788 
    joint1_zero_point: 48020 

arm_solver:
  ros__parameters:
    controller_list: [gravity,friction]
    

