rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Arm -> arm_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmSolver -> arm_solver
      - rmcs_core::controller::pid::PidController -> big_yaw_velocity_pid_controller

      
arm_hardware:
  ros__parameters:
    board_serial_arm_board: "D4-6654-1C0F-7353-AA15-A77B-313D"
    gripper_zero_point: 15504
    joint6_zero_point: 15305
    joint5_zero_point: 21324
    joint4_zero_point: 10417
    joint3_zero_point: 60345
    joint2_zero_point: 26380
    joint1_zero_point: 1881
    big_yaw_zero_point: 40607

arm_solver:
  ros__parameters:
    controller_list: [gravity,friction,zero_torque]

big_yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/big_yaw/velocity
    setpoint: 0.0
    control: /chassis/big_yaw/control_torque
    kp: 1.2
    ki: 0.0
    kd: 0.0
    output_min: -2.0
    output_max: 2.0
    
