rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Arm -> arm_hardware
      - rmcs_core::controller::arm::ArmConfig -> arm_config
      - rmcs_core::controller::arm::ArmSolver -> arm_solver

      
arm_hardware:
  ros__parameters:
    arm_board_usb_pid: 0x488d
    gripper_zero_point: 44185
    joint6_zero_point: 19640
    joint5_zero_point: 47466
    joint4_zero_point: 4017
    joint3_zero_point: 30000
    joint2_zero_point: 54221
    joint1_zero_point: 28268
    big_yaw_zero_point: 20485

arm_solver:
  ros__parameters:
    controller_list: [gravity,friction]
    

