rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Flight -> flight_hardware

flight_hardware:
  ros__parameters:

xrce_dds_agent:
  device: /dev/ttyS0
  baudrate: 921600
