rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Hero -> hero_hardware
      
      - rmcs_core::referee::Status -> referee_status
      - rmcs_core::referee::command::Interaction -> referee_interaction
      - rmcs_core::referee::command::interaction::Ui -> referee_ui
      - rmcs_core::referee::app::ui::Hero -> referee_ui_hero
      - rmcs_core::referee::Command -> referee_command

      - rmcs_core::controller::gimbal::GimbalController -> gimbal_controller
      - rmcs_core::controller::pid::ErrorPidController -> yaw_angle_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller
      # - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller_test
      
      - rmcs_core::controller::gimbal::ShootingController -> shooting_controller
      - rmcs_core::controller::pid::PidController -> second_left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> first_left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> first_right_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> second_right_friction_velocity_pid_controller

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::chassis::OmniWheelController -> omni_wheel_controller

      - rmcs_core::controller::gimbal::PlayerViewer -> gimbal_player_viewer_controller
      # - rmcs_core::controller::pid::ErrorPidController -> viewer_angle_pid_controller

      - rmcs_core::broadcaster::TfBroadcaster -> tf_broadcaster
      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

      - rmcs_core::controller::gimbal::ShootingRecorder -> shooting_recorder
      
      # - rmcs_auto_aim::AutoAimInitializer -> auto_aim_initializer
      # - rmcs_auto_aim::AutoAimController -> auto_aim_controller

pitch_angle_pid_controller_test:
  ros__parameters:
    measurement: /gimbal/pitch/control_angle_error_test
    control: /gimbal/pitch/control_torque
    kp: 50.00
    ki: 0.0
    kd: 0.0

value_broadcaster:
  ros__parameters:
    forward_list:
      - /gimbal/first_left_friction/velocity
      - /gimbal/second_left_friction/velocity
      - /gimbal/first_right_friction/velocity
      - /gimbal/second_right_friction/velocity
      - /gimbal/yaw/angle
      - /gimbal/pitch/angle

hero_hardware:
  ros__parameters:
    usb_pid_top_board: 0xeb37
    usb_pid_bottom_board: 0xc1d3
    yaw_motor_zero_point: 40576
    pitch_motor_zero_point: 54062
    external_imu_port: /dev/ttyUSB0

gimbal_controller:
  ros__parameters:
    upper_limit: -1.2
    lower_limit: 0.4362
    pitch_micro_motion: 0.0001
    yaw_micro_motion: 0.00005

yaw_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/control_angle_error
    control: /gimbal/yaw/control_velocity
    kp: 16.0
    ki: 0.0
    kd: 0.0

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/control_angle_error
    control: /gimbal/pitch/control_velocity
    kp: 20.00
    ki: 0.0
    kd: 0.0

gimbal_player_viewer_controller:
  ros__parameters:
    upper_limit: 0.0058
    lower_limit: 0.6768

shooting_controller:
  ros__parameters:
    friction_wheels:
      - /gimbal/second_left_friction
      - /gimbal/second_right_friction
      - /gimbal/first_left_friction
      - /gimbal/first_right_friction
    friction_velocities:
      - 525.00
      - 525.00
      - 600.00
      - 600.00
    is_42mm: true
    friction_soft_start_stop_time: 1.0
    bullets_per_feeder_turn: 6.0
    shot_frequency: 10.0
    safe_shot_frequency: 10.0
    precise_shot_frequency: 10.0
    eject_frequency: 5.0
    eject_time: 0.2
    deep_eject_frequency: 2.0
    deep_eject_time: 0.5
    single_shot_max_stop_delay: 2.0

shooting_recorder:
  ros__parameters:
    friction_wheel_count: 4
    log_mode: 1 # 1: trigger, 2: timing
    
second_left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/second_left_friction/velocity
    setpoint: /gimbal/second_left_friction/control_velocity
    control: /gimbal/second_left_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

first_left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/first_left_friction/velocity
    setpoint: /gimbal/first_left_friction/control_velocity
    control: /gimbal/first_left_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

first_right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/first_right_friction/velocity
    setpoint: /gimbal/first_right_friction/control_velocity
    control: /gimbal/first_right_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

second_right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/second_right_friction/velocity
    setpoint: /gimbal/second_right_friction/control_velocity
    control: /gimbal/second_right_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

left_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/velocity
    setpoint: /chassis/left_front_wheel/control_velocity
    control: /chassis/left_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/velocity
    setpoint: /chassis/left_back_wheel/control_velocity
    control: /chassis/left_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/velocity
    setpoint: /chassis/right_back_wheel/control_velocity
    control: /chassis/right_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/velocity
    setpoint: /chassis/right_front_wheel/control_velocity
    control: /chassis/right_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

auto_aim_controller:
  ros__parameters:
    # capture
    use_video: false # If true, use video stream instead of camera. 
    video_path: "/workspaces/RMCS/rmcs_ws/resources/1.avi"
    exposure_time: 3
    invert_image: false
    # identifier
    armor_model_path: "/models/mlp.onnx"
    # pnp    
    fx: 1.722231837421459e+03
    fy: 1.724876404292754e+03
    cx: 7.013056440882832e+02
    cy: 5.645821718351237e+02
    k1: -0.064232403853946
    k2: -0.087667493884102
    k3: 0.792381808294582
    # tracker
    armor_predict_duration: 500
    # controller
    gimbal_predict_duration: 100
    yaw_error: 0.02
    pitch_error: 0.06
    shoot_velocity: 28.0
    predict_sec: 0.095
    # etc
    buff_predict_duration: 200
    buff_model_path: "/models/buff_nocolor_v6.onnx"
    omni_exposure: 1000.0
    record_fps: 120
    debug: false # Setup in actual using.Debug mode is used when referee is not ready
    debug_color: 0 # 0 For blue while 1 for red. mine
    debug_robot_id: 4
    debug_buff_mode: false
    record: false
    raw_img_pub: false # Set false in actual use
    image_viewer_type: 2
