rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Infantry -> infantry_hardware
      - rmcs_referee::Status -> referee_status

      - rmcs_core::controller::gimbal::GimbalController -> gimbal_controller
      - rmcs_core::controller::pid::ErrorPidController -> yaw_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> yaw_velocity_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> pitch_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> pitch_velocity_pid_controller

      - rmcs_core::controller::gimbal::ShootingController -> shooting_controller
      - rmcs_core::controller::pid::PidController -> left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> bullet_feeder_velocity_pid_controller

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::chassis::OmniWheelController -> omni_wheel_controller
      - rmcs_core::controller::pid::PidController -> left_front_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> left_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_front_wheel_velocity_pid_controller
      - rmcs_core::controller::chassis::PowerController -> chassis_power_controller

      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

      - rmcs_referee::command::Interaction -> referee_interaction
      - rmcs_referee::command::interaction::Ui -> referee_ui
      - rmcs_referee::app::ui::Infantry -> referee_ui_infantry

      - rmcs_referee::Command -> referee_command

      - rmcs_core::hardware::cboard::GyroCalibrator -> gyro_calibrator
      - rmcs_auto_aim::Controller -> rmcs_auto_aim

infantry_hardware:
  ros__parameters:
    usb_pid: 0x03d9
    yaw_motor_zero_point: 4425
    pitch_motor_zero_point: 6716
    imu_gx_bias: +0.001294
    imu_gy_bias: -0.000584
    imu_gz_bias: +0.000445 # Updated at 30th July 21:28

referee_status:
  ros__parameters:
    path: /dev/ttyUSB0

gimbal_controller:
  ros__parameters:
    upper_limit: -0.4598
    lower_limit: 0.4362

yaw_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/control_angle_error
    control: /gimbal/yaw/control_velocity
    kp: 15.0
    ki: 0.0
    kd: 0.0

yaw_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/yaw/velocity_imu
    setpoint: /gimbal/yaw/control_velocity
    control: /gimbal/yaw/control_torque
    kp: 3.5
    ki: 0.0
    kd: 0.0

pitch_angle_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/control_angle_error
    control: /gimbal/pitch/control_velocity
    kp: 20.00
    ki: 0.0
    kd: 0.0

pitch_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/pitch/velocity_imu
    setpoint: /gimbal/pitch/control_velocity
    control: /gimbal/pitch/control_torque
    kp: 0.8
    ki: 0.0
    kd: 0.0

shooting_controller:
  ros__parameters:
    friction_velocity: 740.0
    shot_frequency: 20.0
    safe_shot_frequency: 10.0

left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/left_friction/velocity
    setpoint: /gimbal/left_friction/control_velocity
    control: /gimbal/left_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/right_friction/velocity
    setpoint: /gimbal/right_friction/control_velocity
    control: /gimbal/right_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

bullet_feeder_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/bullet_feeder/velocity
    setpoint: /gimbal/bullet_feeder/control_velocity
    control: /gimbal/bullet_feeder/control_torque
    kp: 0.583
    ki: 0.0
    kd: 0.0

left_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/velocity
    setpoint: /chassis/left_front_wheel/control_velocity
    control: /chassis/left_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/velocity
    setpoint: /chassis/left_back_wheel/control_velocity
    control: /chassis/left_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/velocity
    setpoint: /chassis/right_back_wheel/control_velocity
    control: /chassis/right_back_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/velocity
    setpoint: /chassis/right_front_wheel/control_velocity
    control: /chassis/right_front_wheel/control_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

chassis_power_controller:
  ros__parameters:
    motors:
      - /chassis/left_front_wheel
      - /chassis/left_back_wheel
      - /chassis/right_back_wheel
      - /chassis/right_front_wheel

rmcs_auto_aim:
  ros__parameters:
    exposure_time: 3
    armor_predict_duration: 500
    buff_predict_duration: 200
    gimbal_predict_duration: 100
    yaw_error: 0.022
    pitch_error: 0.015
    armor_model_path: "/models/mlp.onnx"
    buff_model_path: "/models/buff_nocolor_v6.onnx"
    fx: 1.722231837421459e+03
    fy: 1.724876404292754e+03
    cx: 7.013056440882832e+02
    cy: 5.645821718351237e+02
    k1: -0.064232403853946
    k2: -0.087667493884102
    k3: 0.792381808294582
    omni_exposure: 1000.0
    record_fps: 120
    debug: false # Setup in actual using.Debug mode is used when referee is not ready
    debug_color: 0 # 0 For blue while 1 for red. mine
    debug_robot_id: 5
    debug_buff_mode: true
    record: true
    raw_img_pub: false # Set false in actual use 
    shoot_velocity: 29.0