controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_infantry_chasis_controller:
      type: omni_infantry_chasis_controller/OmniInfantryChasisController

    state_publish_rate: 50.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20

omni_infantry_chasis_controller:
  ros__parameters:
    joints:
      [
        "front_left_wheel",
        "front_right_wheel",
        "back_left_wheel",
        "back_right_wheel",
      ]
    state_joints:
      [
        "front_left_wheel",
        "front_right_wheel",
        "back_left_wheel",
        "back_right_wheel",
      ]
    state_interface_name: ["velocity", "position"]
    cmd_interface_name: ["effort"]
    front_left_wheel:
      pid_data:
        P: 10.0
        I: 0.0
        D: 0.0

    front_right_wheel:
      pid_data:
        P: 10.0
        I: 0.0
        D: 0.0

    back_left_wheel:
      pid_data:
        P: 10.0
        I: 0.0
        D: 0.0

    back_right_wheel:
      pid_data:
        P: 10.0
        I: 0.0
        D: 0.0
