rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::OmniInfantry -> infantry_hardware

      - rmcs_core::referee::Status -> referee_status
      - rmcs_core::referee::Command -> referee_command

      - rmcs_core::referee::command::Interaction -> referee_interaction
      - rmcs_core::referee::command::interaction::Ui -> referee_ui
      - rmcs_core::referee::app::ui::Infantry -> referee_ui_infantry

      - sp_vision_25::bridge::SpVisionBridge -> sp_vision_bridge
      # - rmcs_core::controller::gimbal::VirtualTargetSnapshotProvider -> virtual_target_snapshot_provider
      - rmcs_core::controller::gimbal::OmniInfantryGimbalController -> gimbal_controller
      # - rmcs_core::controller::gimbal::AutoAimResponseRecorder -> auto_aim_response_recorder

      - rmcs_core::controller::shooting::FrictionWheelController -> friction_wheel_controller
      - rmcs_core::controller::shooting::HeatController -> heat_controller
      - rmcs_core::controller::shooting::BulletFeederController17mm -> bullet_feeder_controller
      - rmcs_core::controller::pid::PidController -> left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> bullet_feeder_velocity_pid_controller

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::chassis::ChassisPowerController -> chassis_power_controller
      - rmcs_core::controller::chassis::OmniWheelController -> omni_wheel_controller

infantry_hardware:
  ros__parameters:
    board_serial: ""
    yaw_motor_zero_point: 34754
    pitch_motor_zero_point: 53137

sp_vision_bridge:
  ros__parameters:
    config_file: configs/standard3.yaml
    debug: false

virtual_target_snapshot_provider:
  ros__parameters:
    virtual_valid: true
    virtual_converged: false
    virtual_armor_count: 4
    virtual_armor_type: small
    virtual_armor_name: three

    virtual_center_distance: 2.0
    virtual_center_yaw: 0.0
    virtual_center_height: 0.0
    virtual_center_velocity_x: 0.0
    virtual_center_velocity_y: 0.0
    virtual_center_velocity_z: 0.0
    virtual_angular_velocity: 8.0
    virtual_base_radius: 0.2
    virtual_radius_delta: 0.025
    virtual_height_delta: 0.0
    virtual_initial_phase: 0.0

gimbal_controller:
  ros__parameters:
    bullet_speed_fallback: 23.5
    result_timeout: 0.2

    upper_limit: -0.5098
    lower_limit: 0.2262

    yaw_offset: 1.5
    pitch_offset: 0.8
    decision_speed: 7.0
    high_speed_delay_time: 0.0
    low_speed_delay_time: 0.0
    fire_thresh: 0.01
    max_yaw_acc: 400.0
    max_pitch_acc: 100.0

    yaw_angle_kp: 14.5
    yaw_angle_ki: 0.0
    yaw_angle_kd: 0.0

    yaw_velocity_kp: 6.4
    yaw_velocity_ki: 0.0
    yaw_velocity_kd: 0.0
    
    yaw_vel_ff_gain: 1.0
    yaw_acc_ff_gain: 0.16
    yaw_chassis_spin_torque_ff_gain: -0.22

    pitch_angle_kp: 14.0
    pitch_angle_ki: 0.01
    pitch_angle_kd: 0.1

    pitch_velocity_kp: 5.0
    pitch_velocity_ki: 0.0
    pitch_velocity_kd: 0.0
    
    pitch_vel_ff_gain: 1.0
    pitch_acc_ff_gain: 0.0

auto_aim_response_recorder:
  ros__parameters:
    output_csv_path: /tmp/sp_vision_response_test.csv
    csv_decimation: 1
    require_auto_aim_request: true

friction_wheel_controller:
  ros__parameters:
    friction_wheels:
      - /gimbal/left_friction
      - /gimbal/right_friction
    friction_velocities:
      - 720.0
      - 720.0
    friction_soft_start_stop_time: 1.0

heat_controller:
  ros__parameters:
    heat_per_shot: 10000
    reserved_heat: 10000

bullet_feeder_controller:
  ros__parameters:
    bullets_per_feeder_turn: 8.0
    shot_frequency: 18.0
    safe_shot_frequency: 10.0
    eject_frequency: 10.0
    eject_time: 0.05
    deep_eject_frequency: 5.0
    deep_eject_time: 0.20
    single_shot_max_stop_delay: 2.0

left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/left_friction/velocity
    setpoint: /gimbal/left_friction/control_velocity
    control: /gimbal/left_friction/control_torque
    kp: 0.003436926
    ki: 0.0
    kd: 0.009373434

right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/right_friction/velocity
    setpoint: /gimbal/right_friction/control_velocity
    control: /gimbal/right_friction/control_torque
    kp: 0.003436926
    ki: 0.0
    kd: 0.009373434

bullet_feeder_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/bullet_feeder/velocity
    setpoint: /gimbal/bullet_feeder/control_velocity
    control: /gimbal/bullet_feeder/control_torque
    kp: 1.583
    ki: 0.0
    kd: 0.0
