rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::Sentry -> sentry_hardware

      - rmcs_core::referee::Status -> referee_status
      - rmcs_core::referee::Command -> referee_command
      - rmcs_core::referee::command::Interaction -> referee_interaction
      # - rmcs_core::referee::command::interaction::SentryDecision -> referee_sentry_decision
      - rmcs_core::referee::command::interaction::Ui -> referee_ui

      - rmcs_core::controller::gimbal::EccentricDualYaw -> gimbal_controller
      - rmcs_core::controller::shooting::FrictionWheelController -> friction_wheel_controller
      - rmcs_core::controller::shooting::HeatController -> heat_controller
      - rmcs_core::controller::shooting::BulletFeederController17mm -> bullet_feeder_controller
      - rmcs_core::controller::pid::PidController -> left_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_friction_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> bullet_feeder_velocity_pid_controller
      - rmcs_core::controller::chassis::ChassisClimberController -> climber_controller
      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::chassis::ChassisPowerController -> chassis_power_controller
      - rmcs_core::controller::chassis::SteeringWheelController -> steering_wheel_controller

      - rmcs::navigation::Navigation -> rmcs_navigation

      - rmcs::AutoAimRecorderComponent -> auto_aim_recorder
      - rmcs::AutoAimCapturerComponent -> auto_aim_capturer
      - rmcs::AutoAimComponent -> auto_aim_component

      # - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster
      # - rmcs_core::broadcaster::TfBroadcaster -> tf_broadcaster

rmcs_navigation:
  ros__parameters:
    command_vel_name: "/cmd_vel"
    endpoint: "otaku"
    enable_goal_topic_forward: true

auto_aim_capturer:
  ros__parameters:
    camera_name: ""
    exposure_us: 2000.0
    gain: 8.0
    framerate: 120.0
    invert_image: true
    rls_tau_sec: 10.0
    use_hardware_sync: true
    delay_ms: 6.5

auto_aim_recorder:
  ros__parameters:
    output_path: "/tmp/autoaim/records"
    queue_depth: 16
    flush_every_n_frames: 64
    max_duration_seconds: 0
    max_videos_size_gb: 0.0

auto_aim_component:
  ros__parameters:
    manual_shoot: true
    enable_rune: true
    camera_translation: [0.07128, 0.0, 0.0481]
    fire_control:
      bullet_speed: 22.5
      shoot_delay: 0.1
      offset_yaw: -0.5
      offset_pitch: +1.0
      attack_window: 120.0
      degraded_angle_speed: 12.0
      window_hysteresis: 0.2
      attack_preaim: false
      require_stable_command: false
      yaw_tolerance: 0.07
      pitch_tolerance: 0.04

value_broadcaster:
  ros__parameters:
    forward_list:
      - /gimbal/yaw/velocity_imu
      - /gimbal/pitch/velocity_imu

# The positive direction is the one that battery exists
sentry_hardware:
  ros__parameters:
    board_serial_bottom_board: "af-b4e5"
    board_serial_gimbal_board: "af-8b8b"

    pitch_motor_zero_point: 12453

    bottom_yaw_motor_zero_point: 54253
    top_yaw_motor_zero_point: 32736

    left_front_zero_point: 5776
    left_back_zero_point: 3784
    right_back_zero_point: 3048
    right_front_zero_point: 5135

gimbal_controller:
  ros__parameters:
    upper_limit: -0.65
    lower_limit: 0.36

    top_yaw_angle_kp: 35.0
    top_yaw_angle_ki: 0.008
    top_yaw_angle_kd: 0.005
    top_yaw_velocity_kp: 2.160
    top_yaw_velocity_ki: 0.00
    top_yaw_velocity_kd: 0.0

    bottom_yaw_angle_kp: 16.0
    bottom_yaw_angle_ki: 0.01
    bottom_yaw_angle_kd: 0.0
    bottom_yaw_velocity_kp: 2.75
    bottom_yaw_velocity_ki: 0.00125
    bottom_yaw_velocity_kd: 0.0

    pitch_angle_kp: 32.0
    pitch_angle_ki: 0.01
    pitch_angle_kd: 0.0
    pitch_velocity_kp: 2.5
    pitch_velocity_ki: 0.0
    pitch_velocity_kd: 0.0

chassis_controller:
  ros__parameters:
    angular_velocity_max: 10.0
    translational_velocity_max: 10.0
    following_velocity_kp: 7.0
    following_velocity_ki: 0.0
    following_velocity_kd: 0.0

climber_controller:
  ros__parameters:
    front_climber_velocity: 20.0
    back_climber_velocity: 30.0
    auto_climb_support_retract_velocity_fast: 60.0
    auto_climb_support_retract_velocity_slow: 20.0
    auto_climb_approach_chassis_velocity: 1.0
    auto_climb_support_deploy_chassis_velocity: 0.3
    auto_climb_support_retract_chassis_velocity: 0.3
    auto_climb_dash_chassis_velocity: 3.0
    first_stair_dash_leveled_pitch_threshold: 0.05
    second_stair_dash_leveled_pitch_threshold: -0.09
    sync_coefficient: 0.2
    first_stair_approach_pitch: 0.585
    second_stair_approach_pitch: 0.365
    front_kp: 1.0
    front_ki: 0.0
    front_kd: 0.5
    front_power_estimate_bias: 0.0
    front_power_estimate_k_tau2: 1.0
    front_power_estimate_k_mech: 1.0
    back_kp: 0.5
    back_ki: 0.0
    back_kd: 0.0

friction_wheel_controller:
  ros__parameters:
    friction_wheels:
      - /gimbal/left_friction
      - /gimbal/right_friction
    friction_velocities:
      - 575.0
      - 575.0
    friction_soft_start_stop_time: 1.0

heat_controller:
  ros__parameters:
    heat_per_shot: 10000
    reserved_heat: 30000

bullet_feeder_controller:
  ros__parameters:
    bullets_per_feeder_turn: 9.0
    shot_frequency: 28.0
    safe_shot_frequency: 10.0
    eject_frequency: 15.0
    eject_time: 0.15
    deep_eject_frequency: 15.0
    deep_eject_time: 0.20
    single_shot_max_stop_delay: 2.0

left_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/left_friction/velocity
    setpoint: /gimbal/left_friction/control_velocity
    control: /gimbal/left_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

right_friction_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/right_friction/velocity
    setpoint: /gimbal/right_friction/control_velocity
    control: /gimbal/right_friction/control_torque
    kp: 0.003436926
    ki: 0.00
    kd: 0.009373434

bullet_feeder_velocity_pid_controller:
  ros__parameters:
    measurement: /gimbal/bullet_feeder/velocity
    setpoint: /gimbal/bullet_feeder/control_velocity
    control: /gimbal/bullet_feeder/control_torque
    kp: 0.283
    ki: 0.0
    kd: 0.0

steering_wheel_controller:
  ros__parameters:
    mess: 22.0
    moment_of_inertia: 0.77852676
    vehicle_radius: 0.26870058
    wheel_radius: 0.055
    friction_coefficient: 0.666
    k1: 2.958580e+00
    k2: 3.082190e-03
    no_load_power: 11.37

    chassis_translation_kp: 20.0
    chassis_translation_ki: 0.001
    chassis_translation_kd: 0.00

    chassis_angular_velocity_kp: 8.0
    chassis_angular_velocity_ki: 0.0
    chassis_angular_velocity_kd: 1.0

    steering_velocity_kp: 0.15
    steering_velocity_ki: 0.0
    steering_velocity_kd: 0.0

    steering_angle_kp: 30.0
    steering_angle_ki: 0.0
    steering_angle_kd: 0.0

    wheel_velocity_kp: 0.5
    wheel_velocity_ki: 0.0
    wheel_velocity_kd: 0.0
