rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::cboard::Status -> cboard_status
      # - rmcs_referee::Status -> referee_status

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::pid::ErrorPidController -> left_front_steering_error_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> left_back_steering_error_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> right_back_steering_error_pid_controller
      - rmcs_core::controller::pid::ErrorPidController -> right_front_steering_error_pid_controller
      - rmcs_core::controller::pid::PidController -> left_front_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> left_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_back_wheel_velocity_pid_controller
      - rmcs_core::controller::pid::PidController -> right_front_wheel_velocity_pid_controller
      # - rmcs_core::controller::chassis::PowerController -> chassis_power_controller

      - rmcs_core::broadcaster::ValueBroadcaster -> value_broadcaster

      - rmcs_core::hardware::cboard::Command -> cboard_command

cboard_status:
  ros__parameters:
    path: /dev/ttyACM0
    yaw_motor_zero_point: 3088
    pitch_motor_zero_point: 381
    left_front_motor_zero_point: 4089
    left_back_motor_zero_point: 3410
    right_back_motor_zero_point: 7442
    right_front_motor_zero_point: 1690
    imu_gx_bias: -0.001279
    imu_gy_bias: -0.001447
    imu_gz_bias: +0.002188

# referee_status:
#   ros__parameters:
#     path: /dev/ttyUSB0

left_front_steering_error_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_steering/control_angle_error
    control: /chassis/left_front_steering/control_torque
    kp: 1.0
    ki: 0.00
    kd: 0.01

left_back_steering_error_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_steering/control_angle_error
    control: /chassis/left_back_steering/control_torque
    kp:  1.0
    ki: 0.00
    kd: 0.01

right_back_steering_error_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_steering/control_angle_error
    control: /chassis/right_back_steering/control_torque
    kp:  1.0
    ki: 0.00
    kd: 0.01

right_front_steering_error_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_steering/control_angle_error
    control: /chassis/right_front_steering/control_torque
    kp:  1.0
    ki: 0.00
    kd: 0.01

#=============

left_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/velocity
    setpoint: /chassis/left_front_wheel/control_velocity
    control: /chassis/left_front_wheel/control_torque
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/velocity
    setpoint: /chassis/left_back_wheel/control_velocity
    control: /chassis/left_back_wheel/control_torque
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/velocity
    setpoint: /chassis/right_back_wheel/control_velocity
    control: /chassis/right_back_wheel/control_torque
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_velocity_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/velocity
    setpoint: /chassis/right_front_wheel/control_velocity
    control: /chassis/right_front_wheel/control_torque
    kp: 0.185
    ki: 0.00
    kd: 0.00

# chassis_power_controller:
#   ros__parameters:
#     motors:
#       - /chassis/left_front_steering
#       - /chassis/left_back_steering
#       - /chassis/right_back_steering
#       - /chassis/right_front_steering
#       - /chassis/left_front_wheel
#       - /chassis/left_back_wheel
#       - /chassis/right_back_wheel
#       - /chassis/right_front_wheel
      