rmcs_executor:
  ros__parameters:
    update_rate: 1000.0
    components:
      - rmcs_core::hardware::cboard::Status -> cboard_status
      - rmcs_referee::Status -> referee_status

      - rmcs_core::controller::chassis::ChassisController -> chassis_controller
      - rmcs_core::controller::pid::PidController -> left_front_wheel_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> left_back_wheel_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> right_back_wheel_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> right_front_wheel_angle_pid_controller
      - rmcs_core::controller::pid::PidController -> left_front_wheel_split_pid_controller
      - rmcs_core::controller::pid::PidController -> left_back_wheel_split_pid_controller
      - rmcs_core::controller::pid::PidController -> right_back_wheel_split_pid_controller
      - rmcs_core::controller::pid::PidController -> right_front_wheel_split_pid_controller
      - rmcs_core::controller::chassis::PowerController -> chassis_power_controller

cboard_status:
  ros__parameters:
    path: /dev/ttyACM0
    yaw_motor_zero_point: 3088
    pitch_motor_zero_point: 381
    imu_gx_bias: -0.001279
    imu_gy_bias: -0.001447
    imu_gz_bias: +0.002188

referee_status:
  ros__parameters:
    path: /dev/ttyUSB0

left_front_wheel_angle_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_steering/angle
    setpoint: /chassis/left_front_steering/control_angle
    control: /chassis/left_front_steering/control_angle_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_angle_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_steering/angle
    setpoint: /chassis/left_back_steering/control_angle
    control: /chassis/left_back_steering/control_angle_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_angle_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_steering/angle
    setpoint: /chassis/right_back_steering/control_angle
    control: /chassis/right_back_steering/control_angle_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_angle_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_steering/angle
    setpoint: /chassis/right_front_steering/control_angle
    control: /chassis/right_front_steering/control_angle_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

#===========

left_front_wheel_split_pid_controller:
  ros__parameters:
    measurement: /chassis/left_front_wheel/split
    setpoint: /chassis/left_front_wheel/control_split
    control: /chassis/left_front_wheel/control_split_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

left_back_wheel_split_pid_controller:
  ros__parameters:
    measurement: /chassis/left_back_wheel/split
    setpoint: /chassis/left_back_wheel/control_split
    control: /chassis/left_back_wheel/control_split_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_back_wheel_split_pid_controller:
  ros__parameters:
    measurement: /chassis/right_back_wheel/split
    setpoint: /chassis/right_back_wheel/control_split
    control: /chassis/right_back_wheel/control_split_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

right_front_wheel_split_pid_controller:
  ros__parameters:
    measurement: /chassis/right_front_wheel/split
    setpoint: /chassis/right_front_wheel/control_split
    control: /chassis/right_front_wheel/control_split_torque_unrestricted
    kp: 0.185
    ki: 0.00
    kd: 0.00

chassis_power_controller:
  ros__parameters:
    motors:
      - /chassis/left_front_wheel
      - /chassis/left_back_wheel
      - /chassis/right_back_wheel
      - /chassis/right_front_wheel
      - /chassis/left_front_wheel
      - /chassis/left_back_wheel
      - /chassis/right_back_wheel
      - /chassis/right_front_wheel
