#!/usr/bin/env python3
"""Prepare a V6 bag profile and preview using the production C++ planner."""
from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import subprocess

import yaml

from check_wheel_leg_profile import check
from v6_pair_recording import CALIBRATION, ROOT, RUNS, generate_profile, preview_input


def prepare(run: str, output: Path, *, calibration: Path = CALIBRATION,
            beta_min: float = 65., beta_max: float = 100., preview_dir: Path | None = None,
            preview_bin: Path | None = None) -> dict:
    profile = generate_profile(run, calibration, beta_min=beta_min, beta_max=beta_max)
    errors = check(profile)
    if errors:
        raise ValueError("\n".join(errors))
    p = profile["wheel_leg_pair_identification_controller"]["ros__parameters"]
    manifest = None
    if preview_dir is not None:
        binary = preview_bin or ROOT / "rmcs_ws/install/lib/rmcs_core/wheel_leg_recording_preview"
        if not binary.is_file():
            raise ValueError(f"Build rmcs_core first or pass --preview-bin: {binary}")
        preview_dir.mkdir(parents=True, exist_ok=True)
        plan_path, csv_path = preview_dir / "trajectory-plan.json", preview_dir / "reference-50hz.csv"
        subprocess.run([str(binary.resolve()), str(plan_path), str(csv_path)],
                       input=preview_input(p), text=True, check=True)
        manifest = json.loads(plan_path.read_text())
        manifest.update(calibration_sha256=p["calibration_sha256"],
                        asset_manifest_sha256=p["asset_manifest_sha256"],
                        coordinate_schema="v6_download_link_frames_v1",
                        admitted_beta_deg=[beta_min, beta_max],
                        hip_map=[p["recording_hip_sign"], p["recording_hip_zero"]],
                        reference_preview="nominal; arrival waits, skips and center corrections depend on feedback",
                        control_law="tau=clip(160*(q_held-q)-2.5*dq, -40, 40); no I or feedforward",
                        preview_binary_sha256=hashlib.sha256(binary.read_bytes()).hexdigest(),
                        capacity_status="kinematic budgets checked; torque/load and physical clearance require rig verification")
        plan_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")
        (preview_dir / "calibration.json").write_text(p["calibration_binding_json"])
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("# Generated by prepare_v6_pair_recording.py; edit the versioned binding or generator.\n"
                      + yaml.safe_dump(profile, allow_unicode=True, sort_keys=False))
    return manifest or {"run": run}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run", required=True, choices=RUNS)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("--calibration", type=Path, default=CALIBRATION)
    parser.add_argument("--admitted-beta-min-deg", type=float, default=65.)
    parser.add_argument("--admitted-beta-max-deg", type=float, default=100.)
    parser.add_argument("--preview-dir", type=Path)
    parser.add_argument("--preview-bin", type=Path)
    args = parser.parse_args()
    try:
        result = prepare(args.run, args.output, calibration=args.calibration,
                         beta_min=args.admitted_beta_min_deg, beta_max=args.admitted_beta_max_deg,
                         preview_dir=args.preview_dir, preview_bin=args.preview_bin)
    except (ValueError, OSError, subprocess.CalledProcessError) as error:
        parser.exit(1, f"{error}\n")
    print(f"Prepared {args.run}: {args.output}")
    if "segments" in result:
        print(f"Nominal duration: {result['duration_s']:.2f} s; {len(result['segments'])} segments; "
              "arrival waits can extend the run")


if __name__ == "__main__":
    main()
