#!/usr/bin/env bash
set -eu

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
generated_dir="$SCRIPT_DIR/../.generated"
output_file="$generated_dir/docker-compose.local.override.yml"
repo_root="$(cd "$SCRIPT_DIR/../.." && pwd)"

environment_entries=""
mounts=""

escape_yaml_double_quoted() {
    value=$1
    value=${value//\\/\\\\}
    value=${value//\"/\\\"}
    value=${value//$'\n'/\\n}
    printf '%s' "$value"
}

add_env() {
    env_name=$1
    env_value=$2
    escaped_env_value=$(escape_yaml_double_quoted "$env_value")

    if [ -n "$environment_entries" ]; then
        environment_entries="${environment_entries}      ${env_name}: \"${escaped_env_value}\"\n"
    else
        environment_entries="      ${env_name}: \"${escaped_env_value}\"\n"
    fi
}

add_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        escaped_host_path=$(escape_yaml_double_quoted "$host_path")
        escaped_target_path=$(escape_yaml_double_quoted "$target_path")
        mounts="${mounts}      - type: bind\n        source: \"${escaped_host_path}\"\n        target: \"${escaped_target_path}\"\n"
    fi
}

add_ro_mount() {
    host_path=$1
    target_path=$2

    if [ -e "$host_path" ]; then
        escaped_host_path=$(escape_yaml_double_quoted "$host_path")
        escaped_target_path=$(escape_yaml_double_quoted "$target_path")
        mounts="${mounts}      - type: bind\n        source: \"${escaped_host_path}\"\n        target: \"${escaped_target_path}\"\n        read_only: true\n"
    fi
}

add_env "HOST_WORKSPACE_FOLDER" "$repo_root"

if [ -n "${DISPLAY:-}" ]; then
    add_env "DISPLAY" "$DISPLAY"
fi
if [ -n "${HTTP_PROXY:-}" ]; then
    add_env "HTTP_PROXY" "$HTTP_PROXY"
fi
if [ -n "${HTTPS_PROXY:-}" ]; then
    add_env "HTTPS_PROXY" "$HTTPS_PROXY"
fi
if [ -n "${NO_PROXY:-}" ]; then
    add_env "NO_PROXY" "$NO_PROXY"
fi
if [ -n "${http_proxy:-}" ]; then
    add_env "http_proxy" "$http_proxy"
fi
if [ -n "${https_proxy:-}" ]; then
    add_env "https_proxy" "$https_proxy"
fi
if [ -n "${no_proxy:-}" ]; then
    add_env "no_proxy" "$no_proxy"
fi

add_mount "$HOME/.codex" "/home/ubuntu/.codex"
add_mount "$HOME/.claude" "/home/ubuntu/.claude"
add_mount "$HOME/.claude.json" "/home/ubuntu/.claude.json"
add_mount "$HOME/.lark-cli" "/home/ubuntu/.lark-cli"
add_mount "$HOME/.config/opencode" "/home/ubuntu/.config/opencode"
add_mount "$HOME/.local/share/lark-cli" "/home/ubuntu/.local/share/lark-cli"
add_mount "$HOME/.local/share/opencode" "/home/ubuntu/.local/share/opencode"
add_ro_mount "$HOME/.agents/skills" "/home/ubuntu/.agents/skills"

mkdir -p "$generated_dir"

{
    printf '%s\n' '# Generated by generate-local-override.sh - do not commit'
    printf '%s\n' 'services:'
    printf '%s\n' '  rmcs-develop:'
    printf '%s\n' '    environment:'
    if [ -n "$environment_entries" ]; then
        printf '%b' "$environment_entries"
    else
        printf '%s\n' '      {}'
    fi
    printf '%s\n' '    volumes:'
    if [ -n "$mounts" ]; then
        printf '%b' "$mounts"
    else
        printf '%s\n' '      []'
    fi
} > "$output_file"
