enemy_color: "red"
# enemy_color: "blue"

#神经网络参数
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.8   
use_traditional: true  #改这个

#ROI
roi:
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#tracker参数
min_detect_count: 3 
max_temp_lost_count: 5 
outpost_max_temp_lost_count: 75

#aimer参数
yaw_offset: 0.4 # degree 111
pitch_offset: -1.9 # degree 111
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 5 # rad/s
shoot_time_delay: 0.05    # 固定发射链路延迟 111
high_speed_delay_time: 0.00 # s
low_speed_delay_time: 0.00 # s 
phase_fire_thresh: 6.0       # degree  222
impact_switch_margin: 3.0    # degree  222
impact_select_iters: 5

spin_fire_family_mode: even
spin_phase_fire_window_steps: 2
spin_family_height_margin: 0.01
centerline_enter_speed: 0.0  # 111
centerline_exit_speed: 0.0 # 111

#shooter参数  没有用
first_tolerance: 30 # 近距离射击容差，degree
second_tolerance: 20 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

#相机参数
camera_name: "hikrobot"
exposure_ms: 2.5
gain: 16.9
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1820px
camera_matrix:
  [
    1785.4881526822305,
    0,
    672.4806478241826,
    0,
    1785.026019470562,
    559.89603224794314,
    0,
    0,
    1,
  ]
distort_coeffs:
  [
    -0.076005079619881746,
    0.11182817466388446,
    0.0005362204787722057,
    -0.0027546300984895122,
    0,
  ]

# 理想机械外参（gimbal -> camera）
R_camera2gimbal: [0, 0, 1, -1, 0, 0, 0, -1, 0]
t_camera2gimbal: [0.1420, 0.0, 0.1091] 

#planner参数
fire_thresh: 0.0025

max_yaw_acc: 500
Q_yaw: [9e6, 0] 
R_yaw: [1] 

max_pitch_acc: 100
Q_pitch: [9e6, 0] 
R_pitch: [1] 

