# enemy_color: "red"
enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: CPU
min_confidence: 0.8
use_traditional: true

#####-----ROI-----#####
roi:
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree

#####-----tracker参数-----#####
min_detect_count: 5
max_temp_lost_count: 15
outpost_max_temp_lost_count: 75

#####-----aimer参数-----#####
yaw_offset: 3.3 # degree
pitch_offset: -1.7 # degree
comming_angle: 55 # degree
leaving_angle: 20 # degree
decision_speed: 7 # rad/s
high_speed_delay_time: 0.0 # s
low_speed_delay_time: 0.0 # s planner use this value

#####-----shooter参数-----#####
first_tolerance: 30 # 近距离射击容差，degree
second_tolerance: 20 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击

camera_name: "hikrobot"
exposure_ms: 2.5
gain: 16.9
vid_pid: "2bdf:0001"

#  1  0  0
#  0  1  0
#  0  0  1
R_gimbal2imubody: [1, 0, 0, 0, 1, 0, 0, 0, 1]

# 重投影误差: 0.1820px
camera_matrix:
  [
    1785.4881526822305,
    0,
    672.4806478241826,
    0,
    1785.026019470562,
    559.89603224794314,
    0,
    0,
    1,
  ]
distort_coeffs:
  [
    -0.076005079619881746,
    0.11182817466388446,
    0.0005362204787722057,
    -0.0027546300984895122,
    0,
  ]

# 理想机械外参（gimbal -> camera）
# 理想安装假设: yaw0 pitch0 roll0 degree
R_camera2gimbal: [0, 0, 1, -1, 0, 0, 0, -1, 0]
t_camera2gimbal: [0.02515, 0.0, 0.07985]

#####-----cboard参数-----#####
quaternion_canid: 0x100
bullet_speed_canid: 0x101
send_canid: 0xff
can_interface: "can0"

#####-----gimbal参数-----#####
com_port: "/dev/gimbal"
yaw_kp: 0
yaw_kd: 0
pitch_kp: 0
pitch_kd: 0

#####-----planner-----#####
fire_thresh: 0.0025

max_yaw_acc: 500
Q_yaw: [9e6, 0]
R_yaw: [1]

max_pitch_acc: 100
Q_pitch: [9e6, 0]
R_pitch: [1]

#####-----buff_detector参数-----#####
model: "assets/yolo11_buff_int8.xml"

#####-----buff_aimer参数-----#####
fire_gap_time: 0.700 # s
predict_time: 0.120 # s
