#!/usr/bin/bash

echo "${USBFS_MEMORY_MB:-2000}" >/sys/module/usbcore/parameters/usbfs_memory_mb 2>/dev/null || true

# Remove all files in /tmp
rm -rf /tmp/*

# Remove all files in /run except for /run/dbus
find /run -mindepth 1 -not -path "/run/dbus*" -exec rm -rf {} +

service rmcs start

service ssh start

if [ -f "/etc/avahi/enabled" ]; then
    service avahi-daemon start
fi

sleep infinity
